apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-gpu-ts
  namespace: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: gpu   # Force schedule a node with time slicing support
      tolerations:   # To tolerate the taint on the nodes
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "hub.jupyter.org/dedicated"
        operator: "Equal"
        value: "user"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
