apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: eks
  namespace: flux-system
spec:
  alwaysCleanupRunnerPod: true
  approvePlan: auto
  destroy: false
  destroyResourcesOnDeletion: true
  enableInventory: true
  interval: 1h
  path: ./distributed-databases/cloudnative-postgres
  sourceRef:
    kind: GitRepository
    name: data-on-eks
    namespace: flux-system
  storeReadablePlan: human
  targets:
  - module.eks
  # - kubectl_manifest.aws_auth_configmap
  # - module.eks_managed_node_groups
  dependsOn:
  - name: vpc
  vars:
  - name: name
    value: data-on-eks-cn-postgres
  - name: region
    value: us-west-2
  - name: eks_cluster_version
    value: "1.25"
  - name: vpc_cidr
    value: "10.1.0.0/16"
  varsFrom:
  - kind: Secret
    name: tf-controller-auth
